config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update] do
       resources :comments,only: [:index, :destroy]
    end
    resources :hotels do
      resources :rooms, except: [:index]
    end
    resources :venues, except: [:show]
    resources :services, except: [:show]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get '/users/information/edit' => 'users#edit',as: 'users_edit'
    patch '/users/information' => 'users#update',as: 'users_update'
    get '/users/my_page' => 'users#show',as:'users_show'
    get '/users/check' => 'users#check'
    patch 'users/withdraw' => 'users#withdraw'
    post 'users/sign_out' => 'sessions#destroy'
    resources :hotels, only: [:index, :show] do
      resources :comments
    end
    resources :rooms, only: [:show]
    get '/prefectures_for_region', to: 'prefectures#prefectures_for_region'
    get '/venues_for_prefecture', to: 'venues#venues_for_prefecture'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
   belongs_to :user
   belongs_to :hotel

   validates :comment, presence: true
   validates :star, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true


  GUEST_CUSTOMER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.last_name = "guest"
      customer.first_name = "user"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  def customer_params
    # 必要に応じて許可する属性を指定
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana,:first_name_kana,:email, :is_active)
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :hotel_service_relations
  has_many :services, through: :hotel_service_relations
  has_many :rooms, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :venue, dependent: :destroy
  has_many_attached :images
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :address, presence: true
  validates :venue_id, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :check_in_time_start, presence: true
  validates :check_in_time_end, presence: true
  validates :check_out_time, presence: true
  
  def self.search(search_params)
    hotels = Hotel.all
    hotels = hotels.joins(:venue).where("venues.name LIKE ?", "%#{search_params[:venue]}%") if search_params[:venue].present?
    # 他の検索条件をここに追加
    hotels
  end

  def get_image(width, height)
   unless images.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     images.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
   images[0].variant(resize_to_limit: [width, height]).processed
  end
end

app/models/hotel_service_relation.rb
class HotelServiceRelation < ApplicationRecord
  belongs_to :hotel
  belongs_to :service
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  belongs_to :region
  has_many :venues
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :prefectures
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :bookings
  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :guest, presence: true
  validates :hotel_id, presence: true
  validates :amount, presence: true
  validates :price, presence: true
  validates :checklist, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :hotel_service_relations
  has_many :hotels, through: :hotel_service_relations
  
  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true


  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "guest"
      user.first_name = "user"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  def user_params
    # 必要に応じて許可する属性を指定
    params.require(:user).permit(:last_name, :first_name,:email, :is_active)
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
   belongs_to :prefecture
   has_many :hotels
   
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < ApplicationController

  def new
    @hotel = Hotel.new
    @venues = Venue.all
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      redirect_to admin_hotels_path
    else
     @hotels = Hotel.all # ホテルの保存に失敗した場合に必要
     render :index
    end
  end

  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
    @rooms = @hotel.rooms
  end

  def edit
     @hotel = Hotel.find(params[:id])
     @venues = Venue.all
  end

  def update
    @hotel = Hotel.find(params[:id])
    @hotel.update(hotel_params)
    redirect_to admin_hotel_path
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
    redirect_to admin_hotels_path
  end

   private

  def hotel_params
    params.require(:hotel).permit(:venue_id, :name, :introduction, :address, :latitude, :longitude, :check_in_time_start, :check_in_time_end, :check_out_time, images: [], service_ids: [])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/helpers/admin/bookings_helper.rb
module Admin::BookingsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/hotels_helper.rb
module Admin::HotelsHelper
end

app/helpers/admin/regions_helper.rb
module Admin::RegionsHelper
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/admin/venues_helper.rb
module Admin::VenuesHelper
end

app/helpers/admins/services_helper.rb
module Admins::ServicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/hotels/edit.html.erb
<div class = "container">
  <div class = "col-12">
    <h2 class="text-center", style="color: #48120E">
        ホテル情報編集
    </h2>
  </div>
  <div class = "row justify-content-center pt-5">
    <div class = "col-md-6">
      <div>
        <%= form_with model: @hotel, url: admin_hotel_path(@hotel.id), local:true do |f| %>
          <div class="row my-lg-2">
            <div class="col-3">
              <%= f.label "ホテル画像" %>
            </div>
            <div class="col-7 px-0">
            <%= f.file_field :image, class: "form-control-file image", accept: 'image/*' %>
            </div>
          </div>
          <div class="row my-lg-2">
            <div class="col-3">
              <%= f.label :"ホテル名" %>
            </div>
            <div class="col-7 px-0">
              <%= f.text_field :name, class: 'form-control hotel_name' %>
            </div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3">
               <%= f.label :"ホテル説明" %>
            </div>
            <div class="col-7 px-0">
               <%= f.text_area :introduction, class: 'form-control hotel_introduction',:size=>"40x8"  %>
            </div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3">
               <%= f.label :"住所" %>
            </div>
            <div class="col-7 px-0">
               <%= f.text_field :address, class: 'form-control hotel_address' %>
            </div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3"><%= f.label :"緯度" %></div>
            <div class="col-7 px-0"><%= f.text_field :latitude %></div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3"><%= f.label :"経度" %></div>
            <div class="col-7 px-0"><%= f.text_field :longitude %></div>
          </div>
          <div class="row my-lg-2">
            <div class="col-3">
              <%= f.label :"会場" %>
            </div>
            <div class="col-7 px-0">
              <%= f.select :venue_id, options_for_select(@venues.map { |venue| [venue.name, venue.id] }),
              { include_blank: "-- 選択してください --" }, {required: true, class: +"form-control", id: "venue-select" } %>
            </div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3"><%= f.label :check_in_time_start, "チェックイン開始時間" %></div>
            <div class="col-7 px-0"><%= f.time_field :check_in_time_start %></div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3"><%= f.label :check_in_time_end, "チェックイン終了時間" %></div>
            <div class="col-7 px-0"><%= f.time_field :check_in_time_end %></div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3"><%= f.label :"チェックアウト時間" %></div>
            <div class="col-7 px-0"><%= f.time_field :check_out_time %></div>
          </div>
          <div class='form-group'>
            <%= f.collection_check_boxes(:service_ids, Service.all, :id, :name) do |service| %>
              <div class='form-check'>
                <%= service.label class: 'form-check-label' do %>
                  <%= service.check_box class: 'form-check-input' %>
                  <%= service.text %>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="row my-lg-2 justify-content-md-center ">
            <div class="col-4">
              <div style="border: 2px solid #bee6d8; padding: 2px; border-radius: 5px; text-align: center;">
                <div style="background-color: #bee6d8; border-radius: 5px;">
                  <%= f.submit "変更", class: 'btn btn-lg' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/hotels/index.html.erb
<div class="pt-4">
  <%= link_to "新規登録", new_admin_hotel_path, class:"btn font-bold", style: "background-color: #ffe9a9; color: #1A120B;" %>
  <table class = "table table-hover">
    <thead>
      <tr>
        <th>ホテル</th>
        <th>住所</th>
        <th>付近の会場</th>
        <th>サービス</th>
      </tr>
    </thead>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= link_to admin_hotel_path(hotel.id) do %><%= hotel.name %><% end %></td>
        <td><%= hotel.address %></td>
        <td><%= hotel.venue.try(:name)|| "会場情報がありません" %></td>
        <td><% hotel.services.each do |service|%>
            <%= service.name %>
          <% end %>
        </td>
        <td><%= link_to "削除", admin_hotel_path(hotel.id), method: :delete, data: { confirm: '本当に消しますか？' },remote: true, class: "btn font-bold", style: "background-color: #ffe9a9; color: #1A120B;" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/hotels/new.html.erb
<div class = "container">
  <div class = "col-12">
    <h2 class="text-center", style="color: #48120E">
        ホテル新規登録
    </h2>
  </div>
  <div class = "row justify-content-center pt-5">
    <div class = "col-md-6">
      <div>
        <%= form_with model: @hotel, url: admin_hotels_path, local:true do |f| %>
          <div class="row my-lg-2">
            <div class="col-3">
              <%= f.label "ホテル画像" %>
            </div>
            <div class="col-7 px-0">
            <%= f.file_field :images, name: 'hotel[images[]', multiple: true, class: "form-control-file image", accept: 'image/*' %>
            </div>
          </div>
          <div class="row my-lg-2">
            <div class="col-3">
              <%= f.label :"ホテル名" %>
            </div>
            <div class="col-7 px-0">
              <%= f.text_field :name, class: 'form-control hotel_name' %>
            </div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3">
               <%= f.label :"ホテル説明" %>
            </div>
            <div class="col-7 px-0">
               <%= f.text_area :introduction, class: 'form-control hotel_introduction',:size=>"40x8"  %>
            </div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3">
               <%= f.label :"住所" %>
            </div>
            <div class="col-7 px-0">
               <%= f.text_field :address, class: 'form-control hotel_address' %>
            </div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3"><%= f.label :"緯度" %></div>
            <div class="col-7 px-0"><%= f.text_field :latitude %></div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3"><%= f.label :"経度" %></div>
            <div class="col-7 px-0"><%= f.text_field :longitude %></div>
          </div>
          <div class="row my-lg-2">
            <div class="col-3">
              <%= f.label :"会場" %>
            </div>
            <div class="col-7 px-0">
              <%= f.select :venue_id, options_for_select(@venues.map { |venue| [venue.name, venue.id] }),
              { include_blank: "-- 選択してください --" }, {required: true, class: +"form-control", id: "venue-select" } %>
            </div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3"><%= f.label :check_in_time_start, "チェックイン開始時間" %></div>
            <div class="col-7 px-0"><%= f.time_field :check_in_time_start %></div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3"><%= f.label :check_in_time_end, "チェックイン終了時間" %></div>
            <div class="col-7 px-0"><%= f.time_field :check_in_time_end %></div>
          </div>
          <div class="row my-lg-2 ">
            <div class="col-3"><%= f.label :"チェックアウト時間" %></div>
            <div class="col-7 px-0"><%= f.time_field :check_out_time %></div>
          </div>
          <div class='form-group'>
            <%= f.collection_check_boxes(:service_ids, Service.all, :id, :name) do |service| %>
              <div class='form-check'>
                <%= service.label class: 'form-check-label' do %>
                  <%= service.check_box class: 'form-check-input' %>
                  <%= service.text %>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="row my-lg-2 justify-content-md-center ">
            <div class="col-4">
              <div style="border: 2px solid #bee6d8; padding: 2px; border-radius: 5px; text-align: center;">
                <div style="background-color: #bee6d8; border-radius: 5px;">
                  <%= f.submit "新規登録", class: 'btn btn-lg' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/hotels/show.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-5">
      <div><%= image_tag @hotel.get_image(400,400) %></div>
    </div>
    <% @hotel.images.drop(1).each do |image| %>
      <div><%= image_tag image.variant(resize_to_limit: [250, 200]).processed %></div>
    <% end %>
    <div class = "col-7">
      <div class = "row my-lg-1">
        <div class = col-3 , style="color: #48120E">
          ホテル名
        </div>
        <div class = "col-lg-9", style="color: #48120E">
          <h5><%= @hotel.name %></h5>
        </div>
      </div>
      <div class = "row my-lg-4", style="color: #48120E">
        <div class = col-3>
          ホテル説明
        </div>
        <div class = "col-9", style="color: #48120E">
          <h5><%= @hotel.introduction %></h5>
        </div>
      </div>
      <div class = "row my-lg-4", style="color: #48120E">
        <div class = col-3>
          住所
        </div>
        <div class = "col-9 fs-4", style="color: #48120E">
          <%= @hotel.address %>
        </div>
      </div>
      <div class = "row my-lg-4", style="color: #48120E">
        <div class = col-3>
          会場
        </div>
        <div class = col-9, style="color: #48120E">
          <%= @hotel.venue.try(:name) || "会場情報がありません" %>
        </div>
      </div>
      <div class = "row my-lg-4", style="color: #48120E">
        <div class = col-3>
          チェックイン開始
        </div>
        <div class = col-9, style="color: #48120E">
          <%= @hotel.check_in_time_start.strftime("%H:%M") %>
        </div>
      </div>
      <div class = "row my-lg-4", style="color: #48120E">
        <div class = col-3>
          チェックイン終了
        </div>
        <div class = col-9, style="color: #48120E">
          <%= @hotel.check_in_time_end.strftime("%H:%M") %>
        </div>
      </div>
      <div class = "row my-lg-4", style="color: #48120E">
        <div class = col-3>
          チェックアウト終了
        </div>
        <div class = col-9, style="color: #48120E">
          <%= @hotel.check_out_time.strftime("%H:%M") %>
        </div>
      </div>
      <div class = "row my-lg-4", style="color: #48120E">
        <div class = col-3>
          サービス
        </div>
        <div class = col-9, style="color: #48120E">
          <% @hotel.services.each do |service|%>
            <%= service.name %>
          <% end %>
        </div>
      </div>
    </div>
    <div class = "container">
      <div class = "row my-lg-2 justify-content-center", style="color: #48120E">
        <div class = "col-md-3">
          <div style="border: 2px solid #bee6d8; padding: 2px; border-radius: 5px; text-align: center;">
            <div style="background-color: #bee6d8; border-radius: 5px;">
              <%= link_to '編集する', edit_admin_hotel_path(@hotel), class: "btn btn-lg" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div>
    <%= link_to "ルーム新規登録", new_admin_hotel_room_path(hotel_id: @hotel.id), class:"btn font-bold", style: "background-color: #ffe9a9; color: #1A120B;" %>
  </div>
  <div class = "container">
    <div class = "row">
      <div class = "col-12">
        <table class = "table table-hover">
          <thead>
            <tr>
              <th>部屋タイプ</th>
              <th>宿泊可能人数</th>
              <th>部屋数</th>
              <th>価格</th>
              <th>確認事項</th>
            </tr>
          </thead>
          <% @rooms.each do |room| %>
            <tr>
              <td><%= link_to admin_hotel_room_path(@hotel, room) do %><%= room.name %><% end %></td>
              <td><%= room.guest %></td>
              <td><%= room.amount %></td>
              <td><%= room.price %></td>
              <td><%= room.checklist %></td>
              <td><%= link_to "削除", admin_hotel_room_path(@hotel, room), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn font-bold", style: "background-color: #ffe9a9; color: #1A120B;" %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>