config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update] do
       resources :comments,only: [:index, :destroy]
    end
    resources :hotels do
      resources :rooms, except: [:index]
    end
    resources :venues, except: [:show]
    resources :services, except: [:show]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get '/users/information/edit' => 'users#edit',as: 'users_edit'
    patch '/users/information' => 'users#update',as: 'users_update'
    get '/users/my_page' => 'users#show',as:'users_show'
    get '/users/check' => 'users#check'
    patch 'users/withdraw' => 'users#withdraw'
    post 'users/sign_out' => 'sessions#destroy'
    resources :hotels, only: [:index, :show] do
      resources :comments
    end
    resources :rooms, only: [:show]
    get '/prefectures_for_region', to: 'prefectures#prefectures_for_region'
    get '/venues_for_prefecture', to: 'venues#venues_for_prefecture'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
   belongs_to :user
   belongs_to :hotel

   validates :comment, presence: true
   validates :star, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true


  GUEST_CUSTOMER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.last_name = "guest"
      customer.first_name = "user"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  def customer_params
    # 必要に応じて許可する属性を指定
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana,:first_name_kana,:email, :is_active)
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :hotel_service_relations
  has_many :services, through: :hotel_service_relations
  has_many :rooms, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :venue, dependent: :destroy
  has_many_attached :images
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :address, presence: true
  validates :venue_id, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :check_in_time_start, presence: true
  validates :check_in_time_end, presence: true
  validates :check_out_time, presence: true
  
  def self.search(search_params)
    hotels = Hotel.all
    hotels = hotels.joins(:venue).where("venues.name LIKE ?", "%#{search_params[:venue]}%") if search_params[:venue].present?
    # 他の検索条件をここに追加
    hotels
  end

  def get_image(width, height)
   unless images.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     images.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
   images[0].variant(resize_to_limit: [width, height]).processed
  end
end

app/models/hotel_service_relation.rb
class HotelServiceRelation < ApplicationRecord
  belongs_to :hotel
  belongs_to :service
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  belongs_to :region
  has_many :venues
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :prefectures
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :bookings
  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :guest, presence: true
  validates :hotel_id, presence: true
  validates :amount, presence: true
  validates :price, presence: true
  validates :checklist, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :hotel_service_relations
  has_many :hotels, through: :hotel_service_relations
  
  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true


  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "guest"
      user.first_name = "user"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  def user_params
    # 必要に応じて許可する属性を指定
    params.require(:user).permit(:last_name, :first_name,:email, :is_active)
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
   belongs_to :prefecture
   has_many :hotels
   
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
     @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "会員情報を更新しました。"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :is_active )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/helpers/admin/bookings_helper.rb
module Admin::BookingsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/hotels_helper.rb
module Admin::HotelsHelper
end

app/helpers/admin/regions_helper.rb
module Admin::RegionsHelper
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/admin/venues_helper.rb
module Admin::VenuesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
        <h2 class="text-center", style="color: #48120E">
            <%= @user.last_name %><%= @user.first_name %>さんの会員情報編集
        </h2>
      </div>
    </div>
  </div>
  <div class = "row justify-content-center pt-5">
    <%= form_with model: [:admin, @user], url: admin_user_path(@user.id), method: :patch do |f| %>
      <div class="row pb-3" >
        <div class="col-6 ">
          <h5>会員ID</h5>
        </div>
        <div class="col-6 ">
          <h5><%= @user.id %></h5>
        </div>
      </div>
       <div class="row pb-3" >
        <div class="col-6 ">
          <h5>氏名</h5>
        </div>
        <div class="col-6 ">
          <h5><%= @user.last_name %><%= @user.first_name %></h5>
        </div>
      </div>
      <div class="row pb-3" >
        <div class="col-6 ">
          <h5>メールアドレス</h5>
        </div>
        <div class="col-6 ">
          <h5><%= @user.email %></h5>
        </div>
      </div>
      <div class="row pb-3" >
        <div class="col-6 ">
          <h5>会員ステータス</h5>
        </div>
        <div class="col-6 ">
          <h5><%= f.radio_button :is_active, false %>
          <%= f.label :is_active, "退会" %></h5>
          <h5><%= f.radio_button :is_active, true %>
          <%= f.label :is_active, "有効" %></h5>
        </div>
      </div>
        <div class="row justify-content-md-center">
           <div class = "col-md-6">
              <div style="border: 2px solid #bee6d8; padding: 2px; border-radius: 5px; text-align: center;">
                <div style="background-color: #bee6d8; border-radius: 5px;">
                  <%= f.submit "変更を保存", class:"btn btn-lg" %>
                </div>
              </div>
            </div>
        </div>
      <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class="text-center", style="color: #48120E">
          会員一覧
      </h2>
    </div>
      <table class= "table table-hover">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= link_to admin_user_path(user.id) do %>
                <%= user.last_name %><%= user.first_name %>
                <% end %>
            </td>
            <td><%= user.email %></td>
            <td>
              <% if user.is_active == true %>
                <p class = "text-success">有効</p>
              <% else%>
              　<p class = "text-secondary">退会済</p>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <%= paginate @users %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12  mb-5 mt-3">
      <h4 class="text-center", style="color: #48120E">
        <%= @user.last_name %><%= @user.first_name %>さんの会員詳細
      </h4>
      <table class="table table-borderless" style="color: #48120E;">
        <tr>
          <td>会員ID</td>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @user.last_name %><%= @user.first_name %></td>
        </tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @user.is_active == true %>
              <p class = "text-success">有効</p>
            <% else%>
            　<p class = "text-secondary">退会済</p>
            <% end %>
          </td>
        </tr>
        <tr>
          <td class="d-flex justify-content-center">
            <div style="border: 2px solid #ffe9a9; padding: 2px; border-radius: 5px; text-align: center;">
              <div style="background-color: #ffe9a9; border-radius: 5px;">
                <%= link_to "編集する", edit_admin_user_path, class:"btn" %>
              </div>
            </div>
            <div style="border: 2px solid #bee6df; padding: 2px; border-radius: 5px; text-align: center;">
              <div style="background-color: #bee6df; border-radius: 5px;">
                <%= link_to "レビュー一覧を見る", admin_root_path, class:"btn" %>
              </div>
            </div>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>