config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update] do
       resources :comments,only: [:index, :destroy]
    end
    resources :hotels do
      resources :rooms, except: [:index]
    end
    resources :venues, except: [:show]
    resources :services, except: [:show]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get '/users/information/edit' => 'users#edit',as: 'users_edit'
    patch '/users/information' => 'users#update',as: 'users_update'
    get '/users/my_page' => 'users#show',as:'users_show'
    get '/users/check' => 'users#check'
    patch 'users/withdraw' => 'users#withdraw'
    post 'users/sign_out' => 'sessions#destroy'
    resources :hotels, only: [:index, :show] do
      resources :comments
    end
    resources :rooms, only: [:show]
    get '/prefectures_for_region', to: 'prefectures#prefectures_for_region'
    get '/venues_for_prefecture', to: 'venues#venues_for_prefecture'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
   belongs_to :user
   belongs_to :hotel

   validates :comment, presence: true
   validates :star, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true


  GUEST_CUSTOMER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.last_name = "guest"
      customer.first_name = "user"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  def customer_params
    # 必要に応じて許可する属性を指定
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana,:first_name_kana,:email, :is_active)
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :hotel_service_relations
  has_many :services, through: :hotel_service_relations
  has_many :rooms, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :venue, dependent: :destroy
  has_many_attached :images
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :address, presence: true
  validates :venue_id, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :check_in_time_start, presence: true
  validates :check_in_time_end, presence: true
  validates :check_out_time, presence: true
  
  def self.search(search_params)
    hotels = Hotel.all
    hotels = hotels.joins(:venue).where("venues.name LIKE ?", "%#{search_params[:venue]}%") if search_params[:venue].present?
    # 他の検索条件をここに追加
    hotels
  end

  def get_image(width, height)
   unless images.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     images.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
   images[0].variant(resize_to_limit: [width, height]).processed
  end
end

app/models/hotel_service_relation.rb
class HotelServiceRelation < ApplicationRecord
  belongs_to :hotel
  belongs_to :service
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  belongs_to :region
  has_many :venues
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :prefectures
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :bookings
  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :guest, presence: true
  validates :hotel_id, presence: true
  validates :amount, presence: true
  validates :price, presence: true
  validates :checklist, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :hotel_service_relations
  has_many :hotels, through: :hotel_service_relations
  
  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true


  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "guest"
      user.first_name = "user"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  def user_params
    # 必要に応じて許可する属性を指定
    params.require(:user).permit(:last_name, :first_name,:email, :is_active)
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
   belongs_to :prefecture
   has_many :hotels
   
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/helpers/admin/bookings_helper.rb
module Admin::BookingsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/hotels_helper.rb
module Admin::HotelsHelper
end

app/helpers/admin/regions_helper.rb
module Admin::RegionsHelper
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/admin/venues_helper.rb
module Admin::VenuesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">
    <div class="fixed-top p-2">
      <div class="d-flex content-between align-items-center md-4 ">
        <div class="btn-group">
          <% if user_signed_in? %>
            <%= link_to hotels_path, class: "btn font-bold", class: "header-logo" do %>
              <h2><strong>Live Going</strong></h2>
            <% end %>
          <% else %>
             <%= link_to root_path, class: "btn font-bold", class: "header-logo" do %>
              <h2><strong>Live Going</strong></h2>
            <% end %>
          <% end %>
        </div>
        <div class="btn-group ml-auto">
          <nav class="d-flex align-items-center">
            <ul class="navbar-nav list-group-horizontal ">
              <% if user_signed_in? %>
                <div style="background-color: #e2eda8; border-radius: 5px;">
                  <li class="nav-item"><%= link_to "マイページ", users_show_path, class: "btn font-bold ", style: " color: #48120E;" %></li>
                </div>
                <div style="background-color: #e2eda8; border-radius: 5px;">
                  <li class="nav-item"><%#= link_to "カート", comments_path, class: "btn font-bold ", style: " color: #48120E;"%></li>
                </div>
                <div style="background-color: #d6a5b5; border-radius: 5px;">
                  <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn font-bold ", style: "color: #48120E;"%></li>
                </div>
              <% elsif admin_signed_in? %>
                <div style="background-color: #d6d6a5; border-radius: 5px;">
                  <li class="nav-item"><%= link_to "ホテル一覧", admin_hotels_path, class: "btn font-bold ", style: " color: #48120E;"%></li>
                </div>
                <div style="background-color: #ededa8; border-radius: 5px;">
                  <li class="nav-item"><%= link_to "会員一覧", admin_users_path, class: "btn font-bold ", style: " color: #48120E;"%></li>
                </div>
                <div style="background-color: #ededa8; border-radius: 5px;">
                  <li class="nav-item"><%= link_to "レビュー一覧", admin_root_path, class: "btn font-bold ", style: " color: #48120E;"%></li>
                </div>
                <div style="background-color: #ededa8; border-radius: 5px;">
                  <li class="nav-item"><%= link_to "会場一覧", admin_venues_path, class: "btn font-bold ", style: " color: #48120E;"%></li>
                </div>
                <div style="background-color: #ededa8; border-radius: 5px;">
                  <li class="nav-item"><%= link_to "サービス一覧", admin_services_path, class: "btn font-bold ", style: " color: #48120E;"%></li>
                </div>
                <div style="background-color: #d6a5b5; border-radius: 5px;">
                  <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn font-bold ", style: "background-color: #d6a5b5"%></li>
                </div>
              <% else %>
                <div style="background-color: #a4d5bd; border-radius: 5px;">
                  <li class="nav-item"><%= link_to "ゲストログイン", user_guest_sign_in_path, class: "btn font-bold ", method: :post, style: " color: #48120E;" %></li>
                </div>
                <div style="background-color: #a4d5bd; border-radius: 5px;"><li class="nav-item">
                  <li class="nav-item"><%= link_to "新規登録", new_user_registration_path, class: "btn font-bold", style: "color: #48120E;"%></li>
                </div>
                <div style="background-color: #a5c9d6; border-radius: 5px;">
                  <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: "btn font-bold", style: "color: #48120E;"%></li>
                </div>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiveGoing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/cb055c06a1.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="wrapper">
      <header>
        <%= render 'layouts/header' %>
      </header>
      <main class="inner mt-5 pt-5 container-fluid" style="background-color:#fffff9; color: #48120E;">
        <%= yield %>
      </main>
      <footer>
      </footer>
  </body>
</html>